### ISSUE TITLE
license

### ISSUE THREAD

**Issue by arcturusannamalai** [danieleongari/definitive_screening_design#1]
license is missing for the repository; do you think this package can be published as a open-source license ?

**Comment by danieleongari** [comment]
Since the original author shared the  MatLab software with BSD3 license, I added another one to my work in [f9e4ab2](https://github.com/danieleongari/definitive_screening_design/commit/f9e4ab2d3938487dd580e8e43fb3c76e4664930a)

**Comment by arcturusannamalai** [comment]
thanks mate!
